### ISSUE TITLE
Place Linked Bitmap/Update All Bitmaps not working on Sketch 99.1

### ISSUE THREAD

**Issue by blackmetalben** [frankko/Place-Linked-Bitmap#18]
Not sure if you're still supporting this plug-in, but my design team at lego has found it extremely useful for connecting our psds to our sketch files. Great job on it, whether you update it or not, but I sure hope you do!

Everything still works great, except for the Update All Bitmaps command.

Thanks!

Sincerely,
Ben

**Comment by blackmetalben** [comment]
Sorry… it doesn’t seem to be. I’ve tried it on v100 and v99.5, but the “update all bitmaps” feature isn’t working. “Place bitmap as new layer” and “Place bitmap as layer fill” both work fine.

**Comment by frankko** [comment]
After trying to Update all bitmaps, if you look in ~/Library/Logs/com.bohemiancoding.sketch3/ is there a Plugin Log.log file? You might see an error message related to the plug in there. If you can paste whatever you find, that might help.

**Comment by blackmetalben** [comment]
Does this help?

TypeError: doc. documentData(). assets(). imageCollection is not a function. (In 'doc. documentData(). assets(). imageCollection()', 'doc. documentData(). assets(). imageCollection' is undefined)
    at updateShapeLayer (/Users/usbenfas/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Place Linked Bitmap.sketchplugin/Contents/Sketch/handlers.cocoascript:175:73)
    at PLB_update_bitmaps (/Users/usbenfas/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Place Linked Bitmap.sketchplugin/Contents/Sketch/handlers.cocoascript:404:47)

**Comment by frankko** [comment]
Yes, very much. Thanks. I will get to work.

**Comment by blackmetalben** [comment]
Really appreciate it, man!

**Comment by frankko** [comment]
Sorry about that. Hopefully this one works for you. I appreciate the feedback.

**Comment by blackmetalben** [comment]
Thanks, man! It works perfectly. I have no idea why you're doing this for free, but I'm glad you are!
